"use client";
import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";

// Convex
import { ConvexProvider } from "convex/react";
import { convex } from "@/lib/convex";

// export const metadata: Metadata = {
//   title: "Fin Analysis",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConvexProvider client={convex}>
          <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger className="fixed z-50" />
            {children}
          </SidebarProvider>
        </ConvexProvider>
      </body>
    </html>
  );
}
